- name: Main Playbook
  hosts: all
  tasks:
    - name: Prepare the server
      ansible.builtin.shell: echo "Preparing server"
    
    - name: Deploy the application
      ansible.builtin.shell: echo "Deploying app"

- import_playbook: server_preparation.yml
- import_playbook: deploy_app.yml
