- name: Install docker-compose
  hosts: all
  become: true
  tasks:
    - name: Git kurulu mu?
      ansible.builtin.yum:
        name: git
        state: present
      when: ansible_os_family == "RedHat"
    
    - name: Git kurulu mu?
      ansible.builtin.apt:
        name: git
        state: present
      when: ansible_os_family == "Debian"
    
    - name: Install make
      ansible.builtin.apt:
        name: make
        state: present
        update_cache: yes
    
    - name: GPG anahtarını ekle
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Docker deposunu ekle (Ubuntu/Debian)
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
        state: present
      when: ansible_os_family == "Debian"

    - name: Paket listesini güncelle
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
    
    - name: Docker'ı yükle
      ansible.builtin.apt:
        name: docker-ce
        state: present
      when: ansible_os_family == "Debian"

    - name: Get the latest Docker Compose version
      shell: |
        curl -s https://api.github.com/repos/docker/compose/releases/latest | grep '"tag_name"' | cut -d'"' -f4
      register: compose_version

    - name: Download and install Docker Compose
      shell: |
        curl -L https://github.com/docker/compose/releases/download/{{ compose_version.stdout }}/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
      when: compose_version.stdout is defined


    - name: Make Docker Compose executable
      command: chmod +x /usr/local/bin/docker-compose
    
    - name: Download bash completion for Docker Compose
      command: >
        curl -L https://raw.githubusercontent.com/docker/compose/{{ compose_version.stdout }}/contrib/completion/bash/docker-compose -o /etc/bash_completion.d/docker-compose

    - name: Verify Docker Compose installation
      command: /usr/local/bin/docker-compose -v
      register: compose_version_check

    - name: Show docker-compose version
      debug:
        msg: "Docker Compose version is {{ compose_version_check.stdout }}"
